### ISSUE TITLE
Run-it

### ISSUE THREAD

**Issue by bitionaire** [1and1/itBldz#11]
Yesterday I briefly talked with Matthias if I can implement something like the Grunt watchers in _itBldz_.
As this would be an infinite job - watching files and recompile e.g. less or typescript sources on save - it does not exactly fit into the current goals.

So I suggest a job called e.g. _run-it_ that starts-up the application locally and watches for modifications. Therefore everybody would be able to see the without having any IDE support. 

Just a suggestion, you can decide whether you want to support something like this.

**Comment by MatthiasKainer** [comment]
I think that's a must have; I'd call it different though. Run-it sounds like a follow-up on "build-deploy(-run)"
Any other idea how we could call it?

**Comment by bitionaire** [comment]
_refine-it_, 
_watch-it_, 
_develop-it_, 
_try-it_, 
_repeat-it_, 
_update-it_,
_loop-it_, 
_change-it_, 
_show-it_,
... hard to find something without breaking the _...-it_ terminology. My favorite so fat is **try-it** though it does not suggest that things will get updated on change

**Comment by MatthiasKainer** [comment]
how about 
_workon-it_
_work-on-it_
The on seems stupid though... 

My favorite is _develop-it_, or maybe _dev-it_ for a shorter form. We should do a little coffee-kitchen survey maybe ^^

**Comment by MatthiasKainer** [comment]
I've added acceptance tests for this feature - can you review them and adjust them if needed? 

Feature file is here: https://github.com/1and1/itBldz/blob/RunTasksOnChange/tests/features/UpdateOnChange.feature

**Comment by bitionaire** [comment]
Cucumber test looks good :+1:

**Comment by MatthiasKainer** [comment]
I'm still on this, but it is a bit tricky to get the grunt-watch to play nicely. Maybe we could do a little 2-3h hackingsession together, I'm kinda stuck here atm

**Comment by MatthiasKainer** [comment]
An orgy of 58 commits later a first unstable beta is in the live branch with pull request #30 

You can try it out creating a file _watch.json_ like the following to play around with it 

````json
{
      "scripts": {
            "files": ["<%= config.sources.TypeScript.files %>"],
            "tasks": ["compile/typescript"],
            "options": {
                  "spawn" : false,
                  "perFile": {
                        "targets" : ["default"]
                  }
            }
      }
}
````

The "compile/typescript" task has to be defined in your build.json.
The rest is the same as in a grunt file for the watch without the outer watch:

````js
watch: {
  scripts: {
    files: ['**/*.ts'],
    tasks: ['ts'],
    options: {
      spawn: false,
      perFile : { targets: ["default"] }
    },
  },
}
````

By calling 
````shell
node node_modules/itbldz/itbldz.js watch
````

the watcher starts. Changing a typescript will trigger the task and recompile your TypeScript files
