### ISSUE TITLE
Didn't manage to get grunt-composer to run

### ISSUE THREAD

**Issue by sfudeus** [1and1/itBldz#31]
I tried to use grunt-composer to have a "composer install" running on a project before packaging them via grunt-fpm-package. 
Unfortunately haven't I been able to set the proper cwd to composer, it seems just to ignore it and by that end up in the wrong directory, looking for the composer.json where it cannot be. 
Error-Message:
> Running "composer:install" (composer) task
> Options: (none)
> Options: (none)
> Composer could not find a composer.json file in /media/sf_Workspace/tom-builder
> To initialize a project, please create a composer.json file as described in the https://getcomposer.org/     "Getting Started" section
 > Warning: Task "composer:install" failed. Use --force to continue.

Config:
```json
    "composer": {
      "task": "composer:install",
      "package": "grunt-composer",
      "install": {
        "options": {
            "cwd": "projects/sitebuilder-core"
        }
      }
    },
```

**Comment by MatthiasKainer** [comment]
pls update with newest release and test again. If not working pls reopen ticket

thx,
m
