### ISSUE TITLE
GH pages styling

### ISSUE THREAD

**Issue by jhermann** [1and1/itBldz#9]
Your CSS comes without a background color for `<body>`, and grey (#777) text is nearly unreadable, whatever the background.

**Comment by tkaefer** [comment]
Searching for a colorset that is created to maximize contrast? Have a look at Solarized: http://ethanschoonover.com/solarized

**Comment by MatthiasKainer** [comment]
The current css is from a randomly selected default template for the github pages; rather then fixing the default template I'd have a template that follows the 1&1 CI styles, but I haven't yet had time for this. Help in the form of a pull request would be highly appreciated :)

**Comment by tkaefer** [comment]
Use PFX or Wamba for CI compliance ;)

**Comment by MatthiasKainer** [comment]
I opened a pull request for creating customized github pages based on bootstrap. _build-it_ for page generation. 
@jhermann - is the new design an improvement in your opinion, or should we rather try to go to a CI compliant solution first?
